# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mahasiswa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(584, 575)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(159, 10, 421, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.lineEdit_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 111, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 571, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 520, 571, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 300, 571, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidget)

        self.tableWidget.cellClicked.connect(self.getByid)
        self.pushButton.clicked.connect(self.insertmahasiswa)
        self.pushButton_2.clicked.connect(self.loadmahasiswa)
        self.pushButton_3.clicked.connect(self.Updatemahasiswa)
        self.pushButton_4.clicked.connect(self.Deletemahasiswa)
        self.pushButton_5.clicked.connect(self.searchingmahasiswa)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def getByid(self,row):
        try: 
            npmitem = self. tableWidget.item(row,0)
            namaitem = self.tableWidget.item(row,1)
            kelasitem = self.tableWidget.item(row,2)
            jurusanitem = self.tableWidget.item(row,3)
            Tglitem = self.tableWidget.item(row,4)
            if npmitem :
                valuenpm = npmitem.text()
                valuename = namaitem.text()
                valuekelas = kelasitem.text()
                valuejur = jurusanitem.text()
                valuetgl = Tglitem.text()
                self.lineEdit.setText (valuenpm)
                self.lineEdit_2.setText(valuename)
                self.lineEdit_4.setText(valuekelas)
                self.lineEdit_5.setText(valuejur)
                self.lineEdit_6.setText(valuetgl)
            self.label_3.setText("Data Mahasiswa Berhasil dipilih")
        except mc.Error as err:
            self.label_3.setText("Data Mahasiswa Gagal Dipilih")    

    def insertmahasiswa(self):
        try:
            npm = self.lineEdit.text().strip()
            nama = self.lineEdit_2.text().strip()
            kelas = self.lineEdit_4.text().strip()
            jurusan = self.lineEdit_5.text().strip()
            Tgl = self.lineEdit_6.text().strip()

            if not all([npm, nama, kelas, jurusan, Tgl]):
                self.label_3.setText("Semua field harus diisi!")
                return
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_kampus"
            )
            cursor = mydb.cursor()
            sql = "INSERT INTO mahasiswa (npm, nama, kelas, jurusan, tanggal_lahir) VALUES (%s, %s, %s, %s, %s)"
            val = (npm, nama, kelas, jurusan, Tgl)
            cursor.execute(sql, val)
            mydb.commit()
            self.label_3.setText("Data Mahasiswa Berhasil Disimpan")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")
        except mc.Error as e:
            self.label_3.setText(f"Data Mahasiswa Gagal Disimpan: {e}")

      

    def Updatemahasiswa(self):
        try:
            npm = self.lineEdit.text().strip()
            nama = self.lineEdit_2.text().strip()
            kelas = self.lineEdit_4.text().strip()
            jurusan = self.lineEdit_5.text().strip()
            Tgl = self.lineEdit_6.text().strip()

            if not all([npm, nama, kelas, jurusan, Tgl]):
                self.label_3.setText("Semua field harus diisi!")
                return
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_kampus"
            )
            cursor = mydb.cursor()
            sql = """
                UPDATE mahasiswa
                SET nama = %s, kelas = %s, jurusan = %s, tanggal_lahir = %s
                WHERE npm = %s
            """
            val = (nama, kelas, jurusan, Tgl, npm)
            cursor.execute(sql, val)
            mydb.commit()
            if cursor.rowcount > 0:
                self.label_3.setText("Data Mahasiswa Berhasil Diupdate.")
            else:
               self.label_3.setText("Data Mahasiswa dengan NPM tersebut tidak ditemukan.")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")

        except mc.Error as e:
            self.label_3.setText(f"Data Mahasiswa Gagal Diupdate: {e}")
     
    def Deletemahasiswa(self):
        try:
            npm = self.lineEdit.text().strip()
            if not npm:
                self.label_3.setText("npm mahasiswa tidak boleh kosong!")
                return
            
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_kampus"
            )
            cursor = mydb.cursor()
            sql = "DELETE FROM mahasiswa WHERE npm = %s"
            val = (npm,) 
            cursor.execute(sql, val)
            mydb.commit()
            if cursor.rowcount > 0:
                self.label_3.setText("Data Mahasiswa berhasil dihapus.")
            else:
                self.label_3.setText("Data Mahasiswa tidak ditemukan.")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")

        except mc.Error as e:
            self.label_3.setText(f"Data satuan gagal dihapus: {e}")


    def loadmahasiswa(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_kampus"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM mahasiswa ORDER BY npm ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number,QTableWidgetItem(str(data)))
                    self.label_3.setText("Data Mahasiswa Berhasil Ditampilkan")
        except mc.Error as err:
            self.label_3.setText("Data Mahasiswa Gagal DiLoad")        
    
    def searchingmahasiswa(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_kampus"
            )
            mycursor = mydb.cursor()
            srckat = self.lineEdit_3.text()
            sql = "SELECT * FROM mahasiswa WHERE npm LIKE %s OR nama LIKE %s OR kelas LIKE %s ORDER BY npm ASC"
            val = (f"%{srckat}%", f"%{srckat}%", f"%{srckat}%")
            mycursor.execute(sql, val)
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)

            if result:
                for row_number, row_data in enumerate(result):
                    self.tableWidget.insertRow(row_number)
                    for column_number, data in enumerate(row_data):
                        self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                self.label_3.setText("Hasil Pencarian Data Mahasiswa Ditemukan")
            else:
                self.label_3.setText("Tidak ada data yang ditemukan untuk pencarian.")

        except mc.Error as err:
            self.label_3.setText(f"Pencarian Gagal: {err}")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "NPM"))
        self.label_2.setText(_translate("Form", "Nama "))
        self.label_4.setText(_translate("Form", "Kelas"))
        self.label_5.setText(_translate("Form", "Jurusan"))
        self.label_6.setText(_translate("Form", "Tgl Lahir"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "INSERT"))
        self.pushButton_3.setText(_translate("Form", "UPDATE"))
        self.pushButton_4.setText(_translate("Form", "DELETE"))
        self.pushButton_2.setText(_translate("Form", "LOAD DATA"))
        self.pushButton_5.setText(_translate("Form", "FILTER DATA"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Npm"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Jurusan"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tgl Lahir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
